export const appRoutes = {
  static: {
    contact: '/static/contact',
    terms_of_use: '/static/terms-of-use',
    privacy_policy: '/static/privacy-policy',
  },
  notifications: {
    index: '/notifications/notifications/index',
    purchase_orders_due_today:
      '/notifications/notifications/purchase-orders-due-today',
    overdue_purchase_orders:
      '/notifications/notifications/overdue-purchase-orders',
    expired_subscriptions: '/notifications/notifications/expired-subscriptions',
    subscriptions_about_to_expire:
      '/notifications/notifications/subscriptions-about-to-expire',
  },
  help: {
    index: '/help/help/index',
  },
  administration: {
    users: {
      index: '/administration/users/index',
      create: '/administration/users/create',
      show: '/administration/users/show/details',
      logs: '/administration/users/show/logs',
      inventory_statement: '/administration/users/show/inventory-statement',
      edit: '/administration/users/edit',
      permissions: '/administration/users/permissions',
      change_password: '/administration/users/change-password',
      profile: '/administration/users/profile',
      profile_edit: '/administration/users/profile/edit',
      profile_password: '/administration/users/profile/password',
    },
    documents: {
      index: '/administration/documents',
    },
    accounts: {
      index: '/administration/accounts/index',
      create: '/administration/accounts/create',
      show: '/administration/accounts/show/details',
      edit: '/administration/accounts/edit',
      receipts: '/administration/accounts/show/receipts',
      payments: '/administration/accounts/show/payments',
      deposits: '/administration/accounts/show/deposits',
      withdrawals: '/administration/accounts/show/withdrawals',
      statement: '/administration/accounts/show/statement',
    },
    item_groups: {
      index: '/administration/item-groups/index',
      create: '/administration/item-groups/create',
      show: '/administration/item-groups/show/details',
      edit: '/administration/item-groups/edit',
      items: '/administration/item-groups/show/items',
    },
    bank_accounts: {
      index: '/administration/bank-accounts/index',
      create: '/administration/bank-accounts/create',
      show: '/administration/bank-accounts/show',
      edit: '/administration/bank-accounts/edit',
    },
    unit_of_measures: {
      index: '/administration/unit-of-measures/index',
      create: '/administration/unit-of-measures/create',
      show: '/administration/unit-of-measures/show',
      edit: '/administration/unit-of-measures/edit',
    },
    taxes: {
      index: '/administration/taxes/index',
      create: '/administration/taxes/create',
      show: '/administration/taxes/show/details',
      statement: '/administration/taxes/show/statement',
      edit: '/administration/taxes/edit',
    },
  },
  inventory: {
    items: {
      index: '/inventory/items/index',
      create: '/inventory/items/create',
      show: '/inventory/items/show/details',
      edit: '/inventory/items/edit',
      purchase_order_items: '/inventory/items/show/purchase-order-items',
      stock_returns: '/inventory/items/show/stock-returns',
      stock_issues: '/inventory/items/show/stock-issues',
      statement: '/inventory/items/show/statement',
    },
    purchase_orders: {
      index: '/inventory/purchase-orders/index',
      create: '/inventory/purchase-orders/create',
      show: '/inventory/purchase-orders/show/details',
      preview: '/inventory/purchase-orders/show/preview',
      edit: '/inventory/purchase-orders/edit',
      refunds: '/inventory/purchase-orders/show/refunds',
      payments: '/inventory/purchase-orders/show/payments',
      create_for_item: '/inventory/purchase-orders/create/for-item',
      create_for_supplier: '/inventory/purchase-orders/create/for-supplier',
    },
    stock_issues: {
      index: '/inventory/stock-issues/index',
      create: '/inventory/stock-issues/create',
      show: '/inventory/stock-issues/show',
      edit: '/inventory/stock-issues/edit',
      create_for_item: '/inventory/stock-issues/for-item',
    },
    stock_adjustments: {
      index: '/inventory/stock-adjustments/index',
      create: '/inventory/stock-adjustments/create',
      show: '/inventory/stock-adjustments/show',
      edit: '/inventory/stock-adjustments/edit',
      create_for_item: '/inventory/stock-adjustments/for-item',
    },
    stock_returns: {
      index: '/inventory/stock-returns/index',
      create: '/inventory/stock-returns/create',
      show: '/inventory/stock-returns/show',
      edit: '/inventory/stock-returns/edit',
      create_for_item: '/inventory/stock-returns/create/for-item',
    },
  },
  people: {
    contact_persons: {
      index: '/people/contact-persons/index',
      create: '/people/contact-persons/create',
      show: '/people/contact-persons/show',
      edit: '/people/contact-persons/edit',
      create_for_supplier: '/people/contact-persons/create/for-supplier',
    },
    suppliers: {
      index: '/people/suppliers/index',
      create: '/people/suppliers/create',
      show: '/people/suppliers/show/details',
      edit: '/people/suppliers/edit',
      purchase_orders: '/people/suppliers/show/purchase-orders',
      payments: '/people/suppliers/show/payments',
      refunds: '/people/suppliers/show/refunds',
      statement: '/people/suppliers/show/statement',
      contact_persons: '/people/suppliers/show/contact-persons',
    },
  },
  admissions: {
    applications: {
      index: '/people/applications/index',
      create: '/people/applications/create',
      show: '/people/applications/show',
      edit: '/people/applications/edit',
    },
    transfers: {
      index: '/people/transfers/index',
      create: '/people/transfers/create',
      show: '/people/transfers/show/details',
      edit: '/people/transfers/edit',
    },
  },
  classrooms: {
    classrooms: {
      index: '/people/classrooms/index',
      create: '/people/classrooms/create',
      show: '/people/classrooms/show',
      edit: '/people/classrooms/edit',
    },
    guardians: {
      index: '/people/guardians/index',
      create: '/people/guardians/create',
      show: '/people/guardians/show',
      edit: '/people/guardians/edit',
    },
    issues: {
      index: '/people/issues/index',
      create: '/people/issues/create',
      show: '/people/issues/show',
      edit: '/people/issues/edit',
    },
    teachers: {
      index: '/people/teachers/index',
      create: '/people/teachers/create',
      show: '/people/teachers/show',
      edit: '/people/teachers/edit',
    },
    students: {
      index: '/people/students/index',
      create: '/people/students/create',
      show: '/people/students/show/details',
      edit: '/people/students/edit',
    },
  },
  financials: {
    receipts: {
      index: '/financials/receipts/index',
      create: '/financials/receipts/create',
      show: '/financials/receipts/show',
      edit: '/financials/receipts/edit',
    },
    payments: {
      index: '/financials/payments/index',
      create: '/financials/payments/create',
      show: '/financials/payments/show',
      edit: '/financials/payments/edit',
      create_for_supplier: '/financials/payments/create/for-supplier',
    },
    deposits: {
      index: '/financials/deposits/index',
      create: '/financials/deposits/create',
      show: '/financials/deposits/show',
      edit: '/financials/deposits/edit',
    },
    withdrawals: {
      index: '/financials/withdrawals/index',
      create: '/financials/withdrawals/create',
      show: '/financials/withdrawals/show',
      edit: '/financials/withdrawals/edit',
    },
  },
  settings: {
    show: '/settings/show', //TODO
  },
  subscriptions: {
    index: '/subscriptions/index',
    show: '/subscriptions/show',
  },
  plans: {
    show: '/plans/show',
    subscribe: '/plans/subscribe',
  },
  authentication: {
    login: '/auth/login',
    forgot_password: '/auth/forgot-password',
    reset_password: '/auth/reset-password',
    reset_password_sent: '/auth/reset-password-sent',
    reset_password_updated: '/auth/reset-password-updated',
  },
};
